# Generated by Django 3.1.1 on 2020-09-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restmindapi', '0002_auto_20200908_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='chat',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
