# Generated by Django 3.1.1 on 2020-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restmindapi', '0004_rest_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='newdata',
            fields=[
                ('name', models.CharField(default='name', max_length=20)),
                ('sentiment', models.CharField(default='neutral', max_length=10)),
                ('anger', models.FloatField(default=0.0)),
                ('sad', models.FloatField(default=0.0)),
                ('fear', models.FloatField(default=0.0)),
                ('happy', models.FloatField(default=0.0)),
                ('disgust', models.FloatField(default=0.0)),
                ('surprise', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('chat', models.TextField(default='', max_length=2000)),
                ('mobile_no', models.TextField(max_length=13, primary_key=True, serialize=False)),
            ],
        ),
    ]
