# Generated by Django 3.1.1 on 2020-09-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restmindapi', '0005_newdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newdata',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='mobile_no',
        ),
    ]
