# Generated by Django 3.1.1 on 2020-10-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restmindapi', '0006_auto_20200924_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='unique',
            field=models.CharField(default='abcde12345', max_length=10),
        ),
    ]
